Repository ONLYOFFICE-QA/ooxml_parser, pull requests merged in 2025-02, with the labels that each got.

#1456 Fix `Coordinates#column_number` for multi-chart strings
  CHANGELOG.md
  lib/ooxml_parser/common_parser/common_data/coordinates.rb
  spec/ooxml_parser/coordinates_spec.rb
Labels: bug

#1457 Add parsing `Comment` parameters `author`, `date`, `initials`
  .rubocop_todo.yml
  CHANGELOG.md
  lib/ooxml_parser/docx_parser/document_structure/comments/comment.rb
  spec/document/comments_spec.rb
Labels: enhancement

#1458 Add parsing `CommentExtended#parent_paragraph_id`
  .rubocop_todo.yml
  CHANGELOG.md
  lib/ooxml_parser/docx_parser/document_structure/comments_extended/comment_extended.rb
  spec/document/comments_extended/comment_with_parent_id.docx
  spec/document/comments_extended_spec.rb
Labels: enhancement

#1459 Add parsing `UserProtectedRanges`
  .rubocop_todo.yml
  CHANGELOG.md
  lib/ooxml_parser/xlsx_parser/workbook/worksheet/table_part/extension_list/extension.rb
  lib/ooxml_parser/xlsx_parser/workbook/worksheet/table_part/extension_list/extension/user_protected_ranges.rb
  spec/workbook/worksheet/extensions/user_protected_range/user_protected_range.xlsx
  spec/workbook/worksheet/extensions/user_protected_range/user_protected_range_spec.rb
Labels: enhancement

#1466 Release v0.38.0
  CHANGELOG.md
  Gemfile.lock
  lib/ooxml_parser/version.rb
Labels: release
